name: Liquidity Pipeline CI

on:
  push:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      # -----------------------------
      # FEATURE PIPELINE
      # -----------------------------
      - name: Run Feature Engineering
        run: |
          python 3-src/2-features/1-liquidity_metrics.py
          python 3-src/2-features/2-market_context.py
          python 3-src/2-features/stress_labels.py

      # -----------------------------
      # MODELS
      # -----------------------------
      - name: Run XGBoost
        run: |
          python 3-src/3-models/1-xgboost_engine.py

      - name: Run LSTM
        run: |
          python 3-src/3-models/2-lstm_architecture.py

      # -----------------------------
      # SAVE & PUSH
      # -----------------------------
      - name: Commit & Push Outputs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add models/checkpoints/*
          git commit -m "Auto update models + predictions" || echo "No changes"
          git push
